name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
   name: code linting
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Ruff
      run: |
        pip install ruff

    - name: Run Ruff Linter
      run: |
        # Check for linting issues
        ruff check . --output-format=github
        # Fail if any formatting issue is found
        ruff format --check .
 

  check-env-files:
    name: Check for .env and Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Search for .env Files
        run: |
          if find . -type f -name "*.env" | grep .env; then
            echo "❌ .env file detected. Failing the build."
            exit 1
          else
            echo "✅ No .env files detected."
          fi

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed
        run: |
          echo "CHANGED=$(git diff --name-only origin/${{ github.base_ref }} | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Setup python requirements
        if: contains(env.CHANGED, 'sdk/') || contains(env.CHANGED, 'tests/') || contains(env.CHANGED, 'slack_handlers/') || contains(env.CHANGED, 'api/') || contains(env.CHANGED, '/')
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test SDK AWS
        if: contains(env.CHANGED, 'sdk/aws/') || contains(env.CHANGED, 'sdk/tests/')
        run: |
          python -m pytest sdk/tests/test_runner.py::TestRunner::test_aws

      - name: Test SDK OpenStack
        if: contains(env.CHANGED, 'sdk/openstack/') || contains(env.CHANGED, 'sdk/tests/')
        run: |
          python -m pytest sdk/tests/test_runner.py::TestRunner::test_openstack

      - name: Test SDK Tools
        if: contains(env.CHANGED, 'sdk/tools/') || contains(env.CHANGED, 'sdk/tests/')
        run: |
          python -m pytest sdk/tests/test_runner.py::TestRunner::test_tools

      - name: Test Slack Handlers
        if: (contains(env.CHANGED, 'tests/') && !contains(env.CHANGED, 'sdk/')) || contains(env.CHANGED, 'slack_handlers/')
        run: |
          python -m pytest tests/test_runner.py::TestRunner::test_handlers

      - name: Test Slack Commands
        run: |
          python -m pytest tests/test_runner.py::TestRunner::test_slack_commands
